import { Translations } from './types.ts';

export const USERS_STORAGE_KEY = 'vital-log-users';
export const RECORDS_STORAGE_KEY_PREFIX = 'vital-log-records';

export const translations: { [lang: string]: Translations } = {
  en: {
    title: "VitalLog",
    subtitle: "Blood Pressure & Heart Rate Tracker",
    dashboard: "Dashboard",
    history: "History",
    addNewRecord: "Add New Record",
    systolic: "Systolic (SYS)",
    diastolic: "Diastolic (DIA)",
    heartRate: "Heart Rate (PUL)",
    notes: "Notes (Optional)",
    saveRecord: "Save Record",
    recentRecords: "Recent Records (Last 10)",
    fullHistory: "Full History",
    noRecords: "No records found. Add one to get started!",
    importExport: "Data Management",
    importCSV: "Import from CSV",
    exportCSV: "Export to CSV",
    clearData: "Clear All Data",
    confirmClear: "Are you sure you want to delete all records? This cannot be undone.",
    importSuccess: (count: number) => `Successfully imported ${count} new records.`,
    importDuplicates: (count: number) => `Skipped ${count} duplicate records.`,
    importError: "Invalid file format. Please check the CSV file and try again.",
    recordDeleted: "Record deleted.",
    date: "Date",
    reading: "Reading",
    actions: "Actions",
    delete: "Delete",
    login: "Login",
    register: "Register",
    username: "Username",
    password: "Password",
    logout: "Logout",
    welcomeUser: (name: string) => `Welcome, ${name}`,
    userExists: "Username already exists. Please try another.",
    registrationSuccess: "Registration successful! Please log in.",
    invalidCredentials: "Invalid username or password.",
    loginPrompt: "Already have an account?",
    registerPrompt: "Don't have an account?",
    loginTitle: "Log in to your account",
    registerTitle: "Create a new account",
    loggingIn: "Logging in...",
    registering: "Registering..."
  },
  zh: {
    title: "健康日志",
    subtitle: "血压与心率追踪器",
    dashboard: "仪表盘",
    history: "历史记录",
    addNewRecord: "添加新记录",
    systolic: "收缩压 (SYS)",
    diastolic: "舒张压 (DIA)",
    heartRate: "心率 (PUL)",
    notes: "备注 (可选)",
    saveRecord: "保存记录",
    recentRecords: "最近的记录 (10条)",
    fullHistory: "全部历史记录",
    noRecords: "未找到记录。请添加一条新记录开始！",
    importExport: "数据管理",
    importCSV: "从 CSV 导入",
    exportCSV: "导出为 CSV",
    clearData: "清除所有数据",
    confirmClear: "您确定要删除所有记录吗？此操作无法撤销。",
    importSuccess: (count: number) => `成功导入 ${count} 条新记录。`,
    importDuplicates: (count: number) => `跳过 ${count} 条重复记录。`,
    importError: "文件格式无效。请检查 CSV 文件后重试。",
    recordDeleted: "记录已删除。",
    date: "日期",
    reading: "读数",
    actions: "操作",
    delete: "删除",
    login: "登录",
    register: "注册",
    username: "用户名",
    password: "密码",
    logout: "登出",
    welcomeUser: (name: string) => `欢迎, ${name}`,
    userExists: "用户名已存在，请换一个。",
    registrationSuccess: "注册成功！请登录。",
    invalidCredentials: "用户名或密码无效。",
    loginPrompt: "已有账户？",
    registerPrompt: "没有账户？",
    loginTitle: "登录您的账户",
    registerTitle: "创建新账户",
    loggingIn: "正在登录...",
    registering: "正在注册..."
  }
};